# Generated by Django 4.2.6 on 2023-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_converter_alter_comment_body_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='spoons',
            field=models.IntegerField(default=1, verbose_name='Łyżek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='converter',
            name='factor',
            field=models.IntegerField(verbose_name='Łyżek'),
        ),
        migrations.AlterField(
            model_name='converter',
            name='product',
            field=models.CharField(blank=True, choices=[('Mąka', 'Mąka'), ('Cukier', 'Cukier'), ('Olej', 'Olej'), ('Mleko', 'Mleko'), ('Woda', 'Woda')], max_length=20, verbose_name='Produkt'),
        ),
    ]
