# Generated by Django 4.2.6 on 2023-11-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_product_alter_converter_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('unit', models.CharField(choices=[('mililitr', 'ml'), ('gram', 'gr')], max_length=20, verbose_name='Jednostka')),
            ],
        ),
        migrations.AlterField(
            model_name='converter',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ingredients', verbose_name='Składniki'),
        ),
    ]
