# Generated by Django 4.2.6 on 2023-11-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_ingredients_alter_converter_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
