# Generated by Django 4.2.6 on 2023-11-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('mililitr', 'ml'), ('gram', 'gr')], default=1, max_length=20, verbose_name='Jednostka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='converter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Składniki'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
