# Generated by Django 4.2.6 on 2023-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_product_unit_alter_converter_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('mililitr', 'ml'), ('gram', 'gr')], max_length=20, null=True, verbose_name='Jednostka'),
        ),
    ]
