# Generated by Django 4.2.6 on 2023-11-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='blog.product', verbose_name='Składniki'),
        ),
    ]
