# Generated by Django 4.2.6 on 2023-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_product_weight_product_spoon_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spoon_weight',
            new_name='weight',
        ),
    ]
