# Generated by Django 4.2.6 on 2023-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_product_remove_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('mililitr', 'ml'), ('gram', 'gr'), ('sztuki', 'szt')], default=1, max_length=20, verbose_name='Jednostka'),
            preserve_default=False,
        ),
    ]
