# Generated by Django 3.2.23 on 2023-11-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_ingredient_unit_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
