# Generated by Django 3.2.23 on 2023-11-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20231107_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spoon_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Waga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa produktu'),
        ),
    ]
